[package]
name = "character_creator"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bevy = { version = "0.11.0" }
#bevy_fly_camera = "0.10.0"
bevy_fly_camera = { git = "https://github.com/zachbateman/bevy_fly_camera.git", branch = "bevy_0.11.0" }
#bevy_infinite_grid = "0.7.0"
#bevy_infinite_grid = { git = "https://github.com/PikminGuts92/bevy_infinite_grid.git", branch = "bevy-0.11" }
bevy_infinite_grid = { path = "e:/REPOs-Community/bevy_infinite_grid" }
clap = { workspace = true }
pikaxe = { workspace = true }
pikaxe_bevy = { path = "../../core/pikaxe_bevy" }
log = { workspace = true }