[package]
name = "pikaxe_bevy"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true }
pikaxe = { workspace = true }
futures-lite = { version = "2.3.0" }
log = { workspace = true }
