[package]
name = "pikaxe_bevy"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bevy = { version = "0.10.1", default-features = false, features = [ "bevy_pbr", "bevy_render" ] }
pikaxe = { workspace = true }
futures-lite = { version = "1.13.0" }
log = { workspace = true }